In [2]:
import numpy as np

In [5]:
np.__version__

'1.24.3'

In [6]:
import sys
sys.version

'3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

# Creating List

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

# Convert List to Array

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(my_list)

list

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)

array([], dtype=int32)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [28]:
np.arange(30,20) # 1st arg < 2nd arg as it does not follow the rule hence array is empty

array([], dtype=int32)

In [29]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [30]:
np.arange(10,10)

array([], dtype=int32)

In [31]:
np.arange()

TypeError: arange() requires stop to be specified.

In [32]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [33]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [34]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [39]:
zero = np.zeros([2,2])
print(zero)
type(zero)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [41]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [42]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [45]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [46]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.ones(3)

array([1., 1., 1.])

In [48]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [49]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [50]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
rand(3,2)

NameError: name 'rand' is not defined

In [52]:
random.rand(3,2)

NameError: name 'random' is not defined

In [54]:
rand(3,2)

TypeError: 'module' object is not callable

In [55]:
np.rand(3,2)

AttributeError: module 'numpy' has no attribute 'rand'

In [58]:
np.random.rand(5)

array([0.38691825, 0.48149647, 0.26997561, 0.63190032, 0.2757443 ])

In [60]:
np.random.rand(3,5)

array([[0.85994341, 0.92549745, 0.22446161, 0.17766276, 0.8906902 ],
       [0.38894677, 0.74186167, 0.42729702, 0.97412996, 0.15486156],
       [0.00927733, 0.38407421, 0.14740931, 0.54901367, 0.51424213]])

In [61]:
np.random.randint(4,6)

5

In [63]:
np.random.randint(2,20) #2nd argument is exclusive

2

In [64]:
np.random.randint(0,1)

0

In [65]:
np.random.randint(10,20,5)

array([12, 13, 12, 10, 12])

In [66]:
np.random.randint(1,6,4)

array([5, 2, 5, 5])

In [67]:
np.random.randint(10,20,(3,3))

array([[18, 16, 18],
       [18, 16, 15],
       [16, 14, 11]])

In [68]:
np.random.randint(30,20,10)

ValueError: low >= high

In [69]:
np.random.randint(1,100,(10,10))

array([[22, 79, 43,  2, 75, 82, 42, 22, 84, 53],
       [91,  8, 89, 92, 67,  7, 73, 91, 39, 42],
       [96, 65, 22, 45, 93, 29, 93, 74, 38, 77],
       [34, 77, 56, 48, 26, 55,  1, 18, 80, 86],
       [99, 89, 97, 80, 31, 52, 13, 73, 98, 49],
       [88, 76, 99,  7, 84, 47, 32, 18, 15, 96],
       [32, 52, 95, 73, 81, 63, 84, 12, 70, 41],
       [27, 77, 98, 48, 45, 31, 64, 52, 51, 91],
       [46, 99, 74, 28, 88, 43, 96, 91,  5,  2],
       [24, 61, 60, 57, 39,  1, 58, 84, 66, 98]])

In [73]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [76]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [77]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Slicing in Matrix

In [79]:
b = np.random.randint(10,20,(5,4))
b

array([[10, 10, 14, 18],
       [19, 10, 19, 15],
       [19, 10, 15, 18],
       [11, 13, 16, 19],
       [11, 11, 19, 13]])

In [80]:
type(b)

numpy.ndarray

In [81]:
b

array([[10, 10, 14, 18],
       [19, 10, 19, 15],
       [19, 10, 15, 18],
       [11, 13, 16, 19],
       [11, 11, 19, 13]])

In [82]:
b[:]

array([[10, 10, 14, 18],
       [19, 10, 19, 15],
       [19, 10, 15, 18],
       [11, 13, 16, 19],
       [11, 11, 19, 13]])

In [83]:
b[1:3]

array([[19, 10, 19, 15],
       [19, 10, 15, 18]])

In [84]:
b[::-1]

array([[11, 11, 19, 13],
       [11, 13, 16, 19],
       [19, 10, 15, 18],
       [19, 10, 19, 15],
       [10, 10, 14, 18]])